// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPIOoFV-r77mirPY0XLjcvoqwkp8HM5ao',
    appId: '1:922415439201:web:20f1190dab19bca8c43920',
    messagingSenderId: '922415439201',
    projectId: 'yosrkh20',
    authDomain: 'yosrkh20.firebaseapp.com',
    storageBucket: 'yosrkh20.firebasestorage.app',
    measurementId: 'G-CCFKQT7VGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVOvAnMwn3nlwhKUtnIPvpt5ibmsq5P8Y',
    appId: '1:922415439201:android:e466b7d0bf31cb57c43920',
    messagingSenderId: '922415439201',
    projectId: 'yosrkh20',
    storageBucket: 'yosrkh20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaT63SQ07Ug1RVOtemVJMz2_HrFJyYUmI',
    appId: '1:922415439201:ios:e74df1f6831e2768c43920',
    messagingSenderId: '922415439201',
    projectId: 'yosrkh20',
    storageBucket: 'yosrkh20.firebasestorage.app',
    iosBundleId: 'com.example.ffanilpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaT63SQ07Ug1RVOtemVJMz2_HrFJyYUmI',
    appId: '1:922415439201:ios:e74df1f6831e2768c43920',
    messagingSenderId: '922415439201',
    projectId: 'yosrkh20',
    storageBucket: 'yosrkh20.firebasestorage.app',
    iosBundleId: 'com.example.ffanilpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPIOoFV-r77mirPY0XLjcvoqwkp8HM5ao',
    appId: '1:922415439201:web:e0c8c8779b22f169c43920',
    messagingSenderId: '922415439201',
    projectId: 'yosrkh20',
    authDomain: 'yosrkh20.firebaseapp.com',
    storageBucket: 'yosrkh20.firebasestorage.app',
    measurementId: 'G-49XC2QHC15',
  );
}
